#!/bin/bash
ffmpeg -hide_banner -i static/temp_exp/512x768X.mp4 -vf "fps=60,scale=8000:-1,zoompan=z='pzoom+0.0002':x=iw/2-(iw/zoom/2):y=ih/2-(ih/zoom/2):d=1:s=512x768:fps=60" -c:v libx264 -pix_fmt yuv420p -y outputv.mp4 

ffmpeg -hide_banner -i outputv.mp4 -vf "fps=60,scale=8000:-1,zoompan=z='pzoom+0.0002':x=iw/2-(iw/zoom/2):y=ih/2-(ih/zoom/2):d=1:s=512x768:fps=60,unsharp=3:3:0.5:3:3:0.5" -c:v libx264 -pix_fmt yuv420p -y output_2_v.mp4

ffmpeg -hide_banner -i output_2_v.mp4 -vf "fps=60,scale=8000:-1,zoompan=z='pzoom+0.0002':x=iw/2-(iw/zoom/2):y=ih/2-(ih/zoom/2):d=1:s=512x768:fps=60" -c:v libx264 -pix_fmt yuv420p -y output_3_v.mp4

ffmpeg -hide_banner -i output_3_v.mp4 -vf "fps=60,scale=8000:-1,zoompan=z='pzoom+0.0002':x=iw/2-(iw/zoom/2):y=ih/2-(ih/zoom/2):d=1:s=562x818:fps=60,unsharp=3:3:0.5:3:3:0.5" -c:v libx264 -pix_fmt yuv420p -y static/temp_exp/final_zoom0v.mp4
ffmpeg -hide_banner -i static/temp_exp/final_zoom0v.mp4 -i static/assets/mp4_video_zoom_512x568_border.png -filter_complex "[0:v][1:v]overlay=W-w-0:H-h-0" -codec:a copy -y static/temp_exp/square_zoom_y.mp4

# Choose a random MP3 file from the directory
RANDOM_MP3=$(ls static/mp3s/*.mp3 | shuf -n 1)

# Get the duration of the selected MP3 file
DURATION=$(ffprobe -v error -show_entries format=duration -of csv=p=0 "$RANDOM_MP3")

# Check if the duration was retrieved successfully
if [ -z "$DURATION" ]; then
    echo "Failed to retrieve duration from the audio file."
    exit 1
fi

# Calculate the start time for the fade-out effect (1 second before the end)
FADE_OUT_START=$(echo "$DURATION - 1" | bc)

# Apply a 1-second fade-out to the audio
ffmpeg -i "$RANDOM_MP3" -af "afade=t=out:st=$FADE_OUT_START:d=1" -y static/mp3s/faded_audio.mp3

# Combine the video with the faded audio
ffmpeg -i static/temp_exp/square_zoom_y.mp4 -i static/mp3s/faded_audio.mp3 -c:v copy -c:a aac -b:a 128k -shortest -y static/temp_exp/square_zoomyX.mp4