#!/usr/bin/env python
import glob
import os

files = glob.glob("back*.py")
image_directory = os.getcwd()

# Sort files by creation time
files = sorted(files, key=lambda x: os.path.getctime(os.path.join(image_directory, x)), reverse=True)

# Check if there are more than 2 files before trying to delete
if len(files) > 2:
    for i in range(len(files) - 2):
        print(f"Deleting {files[i]}")
        os.remove(files[i])
else:
    print("Less than 3 files, nothing to delete.")

